import pytest
from application import routes

def test_generator():
    # colour = 'Red'
    for medium in ['Watercolour Paint']:
        for shades in range(2,20):
            for colour in ['Red']:
            assert routes.generator() == (str(shades) + " shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                or routes.generator() == ("2 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                    or routes.generator() == ("2 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                        or routes.generator() == ("2 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                            or routes.generator() == ("2 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                or routes.generator() == ("3 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                    or routes.generator() == ("3 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                        or routes.generator() == ("3 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                            or routes.generator() == ("3 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                or routes.generator() == ("3 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                    or routes.generator() == ("4 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                        or routes.generator() == ("4 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                            or routes.generator() == ("4 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                or routes.generator() == ("4 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                    or routes.generator() == ("4 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                        or routes.generator() == ("5 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                            or routes.generator() == ("5 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                or routes.generator() == ("5 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                    or routes.generator() == ("5 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                        or routes.generator() == ("5 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                            or routes.generator() == ("6 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                or routes.generator() == ("6 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                    or routes.generator() == ("6 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                        or routes.generator() == ("6 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                            or routes.generator() == ("6 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                or routes.generator() == ("7 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                    or routes.generator() == ("7 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                        or routes.generator() == ("7 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                            or routes.generator() == ("7 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                or routes.generator() == ("7 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                    or routes.generator() == ("8 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                        or routes.generator() == ("8 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                            or routes.generator() == ("8 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                or routes.generator() == ("8 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                    or routes.generator() == ("8 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                        or routes.generator() == ("9 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                            or routes.generator() == ("9 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                or routes.generator() == ("9 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                    or routes.generator() == ("9 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                        or routes.generator() == ("9 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                or routes.generator() == ("10 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                        or routes.generator() == ("10 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                or routes.generator() == ("11 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                    or routes.generator() == ("11 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                        or routes.generator() == ("11 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                            or routes.generator() == ("11 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                or routes.generator() == ("11 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                    or routes.generator() == ("12 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                        or routes.generator() == ("12 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                            or routes.generator() == ("12 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                or routes.generator() == ("12 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                    or routes.generator() == ("12 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                        or routes.generator() == ("13 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                            or routes.generator() == ("13 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                or routes.generator() == ("13 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                    or routes.generator() == ("13 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                        or routes.generator() == ("13 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                            or routes.generator() == ("14 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                or routes.generator() == ("14 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                    or routes.generator() == ("14 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                        or routes.generator() == ("14 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                            or routes.generator() == ("14 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                                                or routes.generator() == ("15 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                                    or routes.generator() == ("15 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                                        or routes.generator() == ("15 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                                            or routes.generator() == ("15 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                                                or routes.generator() == ("15 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                                                                    or routes.generator() == ("16 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                                                        or routes.generator() == ("16 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                                                            or routes.generator() == ("16 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                                                                or routes.generator() == ("16 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("16 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("17 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("17 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("17 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("17 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("17 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("18 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("18 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("18 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("18 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("18 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5") \
                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("19 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj1") \
                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("19 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj2") \
                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("19 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj3") \
                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("19 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj4") \
                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("19 shades only using the medium " + medium + " and your Subject is a " + colour + " Obj5")










